name: CI - Docker Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build da imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: taskflow:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max